# This is GitHub Actions workflow deploys the Serverless app 
name: "Deploy SAM Stack to Production"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: for d in */ ; do cd $d && npm install --no-package-lock --loglevel=error && cd .. ; done
      - uses: r0zar/sam-deploy-action@v1.4
        env:
          TEMPLATE: 'template.yaml'
          AWS_STACK_NAME: P2PServerlessStack-${{ github.actor }}
          AWS_REGION: 'us-west-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
